### ISSUE TITLE
Языки программирования

### ISSUE THREAD

**Issue by andersonarc** [DevBuffProject/feedback#4]
В настройках указано ограниченное количество языков программирования, хотя на деле их значительно больше. Я предполагаю, что необходимо добавить возможность указать название ЯП самостоятельно, а категории разработки (бэкенд/фронтенд/...) оставить как есть.

**Comment by BigTows** [comment]
Привет! Спасибо за feedback, изначально мы хотели стандартизировать все навыки, для того чтобы мы могли в будущем сделать хороший поиск и выборку, ведь кто-то может написать `JavaScript`, а кто-то `JS` и это все не очень удобно отслеживать. Соглашусь что сейчас список ЯП не полон. На данном этапе добавление возможно  ЯП, технологий и специальностей возможно только через issuses и обсуждения. Далее планируем что-то типа "голосования", чтобы каждый участник площадки мог заполнить проблемы в предметной области :)
